name: notarize
description: A modern note-taking app with calendar integration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  table_calendar: ^3.0.9
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
fonts:
  - family: Nunito
    fonts:
      - asset: assets/fonts/Nunito-VariableFont_wght.ttf

